# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

dist: trusty

php:
  # Silverstripe 3.x
  # NOTE: Travis-CI is only supporting PHP 5.4+ from late 2017.
  - 5.4

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    #
    # Silverstripe 3.x
    #
    - php: 5.4
      env:
        - DB=MYSQL
        - CORE_RELEASE=3.1
    - php: 5.4
      env:
        - DB=PGSQL
        - CORE_RELEASE=3.2
    - php: 5.5
      env:
        - DB=MYSQL
        - CORE_RELEASE=3.3
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
        - CORE_RELEASE=3

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs union-list/src/ union-list/tests/ -n; fi
  - vendor/bin/phpunit union-list/tests/
